TrajectoryPlannerROS:
  # for details see: https://wiki.ros.org/base_local_planner#TrajectoryPlannerROS
  odom_topic: odom
  global_frame_id: world
  max_vel_x: 0.15
  min_vel_x: 0.01
  max_rotational_vel: 0.1   # 0.1 rad/sec = 5.7 degree/sec

  acc_lim_theta: 0.3
  acc_lim_x: 0.05
  acc_lim_y: 0.05

  holonomic_robot: false
  
  # goal tolerance parameters
  yaw_goal_tolerance: 0.4         # 0.1 means 5.7 degrees
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
  
  # Forward Simulation Parameters
  sim_time: 1                          # The amount of time to forward-simulate trajectories in seconds
  sim_granularity: 0.025               # The step size, in meters, to take between points on a given trajectory
  vx_samples: 10                       # The number of samples to use when exploring the x velocity space
  vtheta_samples: 20                   # The number of samples to use when exploring the theta velocity space

  # Trajectory Scoring Parameters
  meter_scoring: true              # If true, distances are expressed in meters; otherwise grid cells
  goal_distance_bias: 0.7          # The weighting for how much the controller should attempt to reach its local goal, also controls speed

  heading_lookahead: 0.325         # How far to look ahead in meters when scoring different in-place-rotation trajectories
  oscillation_reset_dist: 0.2     # How far the robot must travel in meters before oscillation flags are reset
  publish_cost_grid: true
  dwa: true                       # Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout