local_costmap:
  global_frame: world # sollte odom sein.  global_frame_id param of base_local_planner should be this value
  robot_base_frame: base_link #sollte base_link sein (base_footprint des Roboters)
  update_frequency: 5.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05 #should be same value as in map.yaml file
  origin_x: 0.0
  origin_y: 0.0